// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRH-i-k7ZvfEcpMWtkvdCU-lG6ErnfVD8',
    appId: '1:514022700404:web:fbe90ac3465d0fc23ce821',
    messagingSenderId: '514022700404',
    projectId: 'star-life-5bcb5',
    authDomain: 'star-life-5bcb5.firebaseapp.com',
    storageBucket: 'star-life-5bcb5.firebasestorage.app',
    measurementId: 'G-KZ7TJ2JGBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9J60dFa8t-RdDDVuHC6_QlEQD0nj4Wko',
    appId: '1:514022700404:android:dcb7e70795fefc833ce821',
    messagingSenderId: '514022700404',
    projectId: 'star-life-5bcb5',
    storageBucket: 'star-life-5bcb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLv-Hu6rXl4hWQhkSBn6I7673YVz4r9uo',
    appId: '1:514022700404:ios:d439d4c5355c991f3ce821',
    messagingSenderId: '514022700404',
    projectId: 'star-life-5bcb5',
    storageBucket: 'star-life-5bcb5.firebasestorage.app',
    iosClientId: '514022700404-p9raaqkhb702lei7nqvdoate913qikjv.apps.googleusercontent.com',
    iosBundleId: 'com.example.boxhub',
  );
}
